### ISSUE TITLE
Add some missing stuff: mode

### ISSUE THREAD

**Issue by autarch** [houseabsolute/List-SomeUtils#2]
Migrated from [rt.cpan.org #121490](https://rt.cpan.org/Ticket/Display.html?id=121490) (status was 'open')

Requestors:
* jpierce@cpan.org

From jpierce@cpan.org on 2017-05-01 18:14:00:

Will return most common value(s), and unlike the mode in Statistics::Descriptive and Statistics::Basic, works with text as well as numbers.

sub mode{
  my %F;
  $F{$_}++ foreach @_;
  my $max = $F{ (sort { $F{$b}<=>$F{$a} } keys %F)[0] };
  grep { $F{$_}==$max } keys %F;
}

**Comment by autarch** [comment]
From jpierce@cpan.org on 2017-05-02 00:40:04:

On Mon May 01 14:14:00 2017, JPIERCE wrote:
> Will return most common value(s), and unlike the mode in
> Statistics::Descriptive and Statistics::Basic, works with text as well
> as numbers.
> 
> sub mode{
>   my %F;
>   $F{$_}++ foreach @_;
>   my $max = $F{ (sort { $F{$b}<=>$F{$a} } keys %F)[0] };
>   grep { $F{$_}==$max } keys %F;
> }

Slightly less elegant, but more robust:

sub mode{
    my %F;
    $F{$_}++ foreach grep { defined } @_;
    my $max = $F{ (sort { $F{$b}<=>$F{$a} } keys %F)[0] };
    my @modes = grep { $F{$_}==$max } keys %F;
    return wantarray() ? @modes : (scalar @modes > 1 ? undef : $modes[0]);
}

This will return undef  in scalar context if more than one mode exists. The previous version would permit undef as a valid data point/mode, but in scalar context you'd end up with the number of modes for your data rather than the actual mode, even for a unimodal data set.

Alternatively, keep the previous version and simply note in documentation that it must always be called in list context....

**Comment by autarch** [comment]
From drolsky@cpan.org (@autarch) on 2017-06-01 19:59:26:

On 2017-05-01 19:40:04, JPIERCE wrote:
> On Mon May 01 14:14:00 2017, JPIERCE wrote:
> > Will return most common value(s), and unlike the mode in
> > Statistics::Descriptive and Statistics::Basic, works with text as
> > well
> > as numbers.
> >
> > sub mode{
> >   my %F;
> >   $F{$_}++ foreach @_;
> >   my $max = $F{ (sort { $F{$b}<=>$F{$a} } keys %F)[0] };
> >   grep { $F{$_}==$max } keys %F;
> > }
> 
> Slightly less elegant, but more robust:
> 
> sub mode{
>     my %F;
>     $F{$_}++ foreach grep { defined } @_;
>     my $max = $F{ (sort { $F{$b}<=>$F{$a} } keys %F)[0] };
>     my @modes = grep { $F{$_}==$max } keys %F;
>     return wantarray() ? @modes : (scalar @modes > 1 ? undef :
> $modes[0]);
> }
> 
> This will return undef  in scalar context if more than one mode
> exists. The previous version would permit undef as a valid data
> point/mode, but in scalar context you'd end up with the number of
> modes for your data rather than the actual mode, even for a unimodal
> data set.
> 
> Alternatively, keep the previous version and simply note in
> documentation that it must always be called in list context....

This looks useful, but I think to add any new subs I'd also want to add an XS version to List-SomeUtils-XS. Any chance you'd be up for that?

Also, I'm about to move this issue queue to GitHub ...

**Comment by belg4mit** [comment]
Alas, I'm not much of a C programmer.

**Comment by autarch** [comment]
It's probably within my capabilities to implement a C version. I will add it to the round tuit list.
